# Generated by Django 6.0.7 on 2026-07-27 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(help_text='e.g., LHR-1234 or BUS-301', max_length=250, unique=True)),
                ('total_seats', models.IntegerField(default=40, help_text='Total bookable seats on this bus')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(help_text='e.g., Lahore Express', max_length=255)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled (Low Occupancy / Emergency)'), ('COMPLETED', 'Completed')], default='SCHEDULED', help_text='Changing to CANCELLED will allow refund tracking for passengers', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bookings.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('fare_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_cnic', models.CharField(help_text='Format: 35202-1234567-1', max_length=15)),
                ('passenger_email', models.EmailField(help_text='Used for OTP dispatch and e-tickets', max_length=254)),
                ('passenger_phone', models.CharField(max_length=20)),
                ('pnr_number', models.CharField(editable=False, help_text='Unique 8-character booking reference', max_length=8, unique=True)),
                ('verification_code', models.CharField(blank=True, help_text='6-digit email OTP', max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='True once email OTP is successfully verified')),
                ('payment_status', models.CharField(choices=[('PENDING_TERMINAL', 'Pending Terminal Cash Payment'), ('PAID_ONLINE', 'Paid Online'), ('PAID_TERMINAL', 'Paid at Terminal Desk'), ('REFUNDED', 'Refunded')], default='PENDING_TERMINAL', max_length=20)),
                ('ticket_status', models.CharField(choices=[('PENDING_OTP', 'Pending Email OTP Verification'), ('RESERVED', 'Reserved (Awaiting Payment)'), ('CONFIRMED', 'Confirmed & Paid'), ('CANCELLED_USER', 'Cancelled by Passenger'), ('CANCELLED_COMPANY', 'Cancelled by Bus Company')], default='PENDING_OTP', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_destinations', to='bookings.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_origins', to='bookings.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('trip', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='FareMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_destinations', to='bookings.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_origins', to='bookings.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='bookings.trip')),
            ],
            options={
                'unique_together': {('trip', 'origin', 'destination')},
            },
        ),
    ]
