# Generated by Django 6.0.7 on 2026-07-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger_cnic',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('PENDING_TERMINAL', 'Pending Terminal Cash Payment'), ('PENDING_ONLINE', 'Pending Online Payment'), ('PAID_TERMINAL', 'Paid at Terminal Counter'), ('PAID_ONLINE', 'Paid Online'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded')], default='PENDING_TERMINAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr_number',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('PENDING_OTP', 'Pending OTP Verification'), ('RESERVED', 'Reserved (Awaiting Payment)'), ('CONFIRMED', 'Confirmed & Paid'), ('CANCELLED_USER', 'Cancelled by Passenger'), ('CANCELLED_COMPANY', 'Cancelled by Bus Company')], default='PENDING_OTP', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20),
        ),
    ]
