# Generated by Django 6.0.7 on 2026-07-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bus_bus_number_alter_bus_total_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('payment_option_1', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_option_2', models.CharField(blank=True, max_length=20, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Additional payment instructions')),
            ],
        ),
        migrations.RenameModel(
            old_name='FareMatrix',
            new_name='FareCalculation',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='bus_number',
            new_name='bus_name',
        ),
    ]
