# Generated by Django 6.0.7 on 2026-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_paymentconfig_rename_farematrix_farecalculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sender_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
