# Generated by Django 6.0.7 on 2026-07-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_ticket_sender_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to retire a bus without deleting historical tickets.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_destinations', to='bookings.location'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_origins', to='bookings.location'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('PENDING_TERMINAL', 'Pending Terminal Cash Payment'), ('PENDING_ONLINE', 'Pending Online Payment'), ('PAID_TERMINAL', 'Paid at Terminal Counter'), ('PAID_ONLINE', 'Paid Online'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled (No Payment Owed)')], default='PENDING_TERMINAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('PENDING_OTP', 'Pending OTP Verification'), ('RESERVED', 'Reserved (Awaiting Payment)'), ('CONFIRMED', 'Confirmed & Paid'), ('CANCELLED_USER', 'Cancelled by Passenger'), ('CANCELLED_COMPANY', 'Cancelled by Bus Company'), ('CANCELLED', 'Cancelled (No Payment Owed)')], default='PENDING_OTP', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='bookings.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='bookings.bus'),
        ),
    ]
