# Generated by Django 6.0.7 on 2026-07-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bus_is_active_alter_ticket_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farecalculation',
            name='segment_arrival_time',
            field=models.TimeField(blank=True, help_text='Time bus arrives at this specific destination', null=True),
        ),
        migrations.AddField(
            model_name='farecalculation',
            name='segment_departure_time',
            field=models.TimeField(blank=True, help_text='Time bus leaves this specific origin', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
